const colors = {
  light: {
    background: "#F8F9FD",
    foreground: "#0D1B2A",
    card: "#FFFFFF",
    cardForeground: "#0D1B2A",
    primary: "#1B4F8A",
    primaryForeground: "#FFFFFF",
    secondary: "#E8F0FE",
    secondaryForeground: "#1B4F8A",
    muted: "#F1F4F9",
    mutedForeground: "#6B7897",
    accent: "#D4AF37",
    accentForeground: "#0D1B2A",
    destructive: "#DC2626",
    destructiveForeground: "#FFFFFF",
    border: "#E2E8F4",
    input: "#E2E8F4",
    text: "#0D1B2A",
    tint: "#1B4F8A",
    success: "#16A34A",
    warning: "#D97706",
  },
  dark: {
    background: "#0D1B2A",
    foreground: "#F8F9FD",
    card: "#1A2942",
    cardForeground: "#F8F9FD",
    primary: "#4A90D9",
    primaryForeground: "#FFFFFF",
    secondary: "#1E3A5F",
    secondaryForeground: "#A8C4E8",
    muted: "#1A2942",
    mutedForeground: "#8BA3C7",
    accent: "#D4AF37",
    accentForeground: "#0D1B2A",
    destructive: "#EF4444",
    destructiveForeground: "#FFFFFF",
    border: "#1E3A5F",
    input: "#1E3A5F",
    text: "#F8F9FD",
    tint: "#4A90D9",
    success: "#22C55E",
    warning: "#F59E0B",
  },
  radius: 12,
};

export default colors;