import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import dashboardRouter from "./dashboard";
import propertiesRouter from "./properties";
import tenantsRouter from "./tenants";
import paymentsRouter from "./payments";
import expensesRouter from "./expenses";
import loansRouter from "./loans";
import maintenanceRouter from "./maintenance";
import reportsRouter from "./reports";
import agreementsRouter from "./agreements";
import documentsRouter from "./documents";
import backupRouter from "./backup";
import businessSettingsRouter from "./business-settings";
import generatedRentsRouter from "./generated-rents";
import activityLogsRouter from "./activity-logs";
import remindersRouter from "./reminders";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(dashboardRouter);
router.use(propertiesRouter);
router.use(tenantsRouter);
router.use(paymentsRouter);
router.use(expensesRouter);
router.use(loansRouter);
router.use(maintenanceRouter);
router.use(reportsRouter);
router.use(agreementsRouter);
router.use(documentsRouter);
router.use(backupRouter);
router.use(businessSettingsRouter);
router.use(generatedRentsRouter);
router.use(activityLogsRouter);
router.use(remindersRouter);

export default router;
